### ISSUE TITLE
SYN Flooding Attack Not Happening

### ISSUE THREAD

**Issue by efak** [mjdubell/SYN-Flooder#6]
I am testing the code with two VMs. My goal is to bring down the telnet server running on one of the VMs using SYN Flooding attack. I have tried both the single and multiprocessing versions without success. 

Running `netstat -tna` indicates the attack is unsuccessful as seen in screenshot below:
![netstat](https://user-images.githubusercontent.com/24601259/53474354-d6eed000-3a3a-11e9-9933-18d17ffce631.png)

I also ensured the SYN flooding countermeasure on Ubuntu is also turned off with ` sudo sysctl -w net.ipv4.tcp_syncookies=0`

Any help in figuring out why the the code is not working for me will be appreciated. For now, my hypothesis is that Python is not sending the SYN packets at a desirable rate. I say that because I  wrote my own C code to achieve the SYN flooding attack.

**Comment by dubs3c** [comment]
That is strange, you should see a lot of connections in `WAIT` state. Are you sure you are "attacking" the correct IP?

The purpose of this tool was never to be used as an _actual_ tool for bringing down systems, just to show in code how it works.  I will try it later on my own systems to verify that it works.

**Comment by efak** [comment]
Thanks for responding Mike.
Yes I am sure of the IP. I have used Wireshark to verify that the spoofed packets have the correct destination IP. 
I understand it may not bring down server but at least I expected to see some results when I run `netstat`

**Comment by dubs3c** [comment]
@efak I just verified on my servers and it worked, I got bunch of connections immediately. Do you have any firewalls blocking the packets?

**Comment by efak** [comment]
Interesting to know.
I do not have any firewall configured on the two VMs. My VMs are running Ubuntu 16.04.

**Comment by efak** [comment]
I am looking at tcpdump and looks like the target VM is responding with RST packets:
![tcpdump](https://user-images.githubusercontent.com/24601259/53530662-9769c780-3abe-11e9-9d04-6865c6f4b10d.png)

**Comment by dubs3c** [comment]
Try changing this line: https://github.com/mjdubell/SYN-Flooder/blob/master/syn_flooder.py#L31

to "10.0.2."

**Comment by dubs3c** [comment]
@efak Did you manage to fix the issue?

**Comment by efak** [comment]
@mjdubell No Mike, it did not. See screenshot below:

![Screenshot from 2019-03-08 15 32 18](https://user-images.githubusercontent.com/24601259/54054321-e64ae780-41b7-11e9-9ca4-853fd4333076.png)

**Comment by dubs3c** [comment]
Does your syn flooder program work? Can you see connections with netstat?

**Comment by efak** [comment]
I do not see connections with netstat

**Comment by dubs3c** [comment]
@efak Then it seems something is wrong with your VM setup :/
